apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::243897321215:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Y8CTTVN0GK3U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:  
      - system:masters
      rolearn: arn:aws:iam::243897321215:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-29T17:43:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1712"
  uid: 30027710-c3f3-4c81-bb0a-90e4e4f62adc
