apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::243897321215:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1J5GBFTC87T7M
      username: system:node:{{EC2PrivateDNSName}}
    - groups:  
      - system:masters
      rolearn: arn:aws:iam::243897321215:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-03T18:20:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1708"
  uid: dc5303c2-69a3-417e-9177-c8b8dce3c033
